backend:
  image: supriya9820/python3tier-backend
  tag: latest
  replicas: 2
  port: 8000

frontend:
  image: supriya9820/python3tier-frontend
  tag: latest
  replicas: 2
  port: 80
  nodePort: 30080

postgres:
  image: postgres:15
  db: tasksdb
  user: admin
  password: admin
